import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './Components/Common/Header'
import Navbar from "./Components/Common/Navbar";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#333333] lg:px-48">
        <Header/>
        {children}
        <Navbar/>
      </body>
    </html>
  );
}
